### ISSUE TITLE
problem with i2c setup

### ISSUE THREAD

**Issue by nonsintetic** [kd7yva/oled-js-pi#4]
Hello!

I'm getting the following error when trying to access a 128x64 i2c oled screen on my RPI 3:

when running with:

```
var opts = {
  width: 128,
  height: 64,
  address: 0x3c
};
var oled = new oled(opts);
```

i get

```
this.ADDRESS: 60
/home/pi/Work/DHT11/node_modules/oled-js-pi/node_modules/i2c/lib/i2c.coffee:65
      wire.setAddress(address);
           ^
TypeError: Failed to set address
  at TypeError (native)
  at i2c.setAddress (/home/pi/Work/DHT11/node_modules/oled-js-pi/node_modules/i2c/lib/i2c.coffee:38:10)
  at i2c.writeByte (/home/pi/Work/DHT11/node_modules/oled-js-pi/node_modules/i2c/lib/i2c.coffee:57:6)
  at [object Object].Oled._transfer (/home/pi/Work/DHT11/node_modules/oled-js-pi/oled.js:120:13)
  at [object Object].Oled._initialise (/home/pi/Work/DHT11/node_modules/oled-js-pi/oled.js:103:10)
  at new Oled (/home/pi/Work/DHT11/node_modules/oled-js-pi/oled.js:74:8)
  at Object.<anonymous> (/home/pi/Work/DHT11/app.js:27:12)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

I looked up the address using  `i2cdetect -y 1` and I get the address 3c so it is recognized by the RPi. The screen works fine with my Arduino so it's not a hardware issue either.

**Comment by nonsintetic** [comment]
Ok, I've figured it out:

in the library the device used is hardcoded to i2c-0, this only works on the old RPIs. On the new ones the i2c port was moved to i2c-1. All you need to fix it is to change line 68 in olded.js to:

this.wire = new i2c(this.ADDRESS, {device: '/dev/**i2c-1**'});

**Comment by dustinbolton** [comment]
I was also able to fix this to work with the RaspBerry Pi 2 b by changing:
this.wire = new i2c(this.ADDRESS, {device: '/dev/i2c-0'});
To:
this.wire = new i2c(this.ADDRESS, {device: '/dev/i2c-1'});

Would be good to fix this or note it in documentation for setup at least. :)
