### ISSUE TITLE
TypeError: Cannot read property 'writeByte' of undefined

### ISSUE THREAD

**Issue by JMishou** [kd7yva/oled-js-pi#6]
This is the same error code as the previous issues #1 & #3 but the code seems to have been corrected since those issues were reported.

Here is the error code

```
/home/pi/node_modules/oled-js-pi/oled.js:121
    this.wire.writeByte(val, function(err) {
             ^

TypeError: Cannot read property 'writeByte' of undefined
  at /home/pi/node_modules/oled-js-pi/oled.js:121:14
  at Immediate._onImmediate (/home/pi/node_modules/oled-js-pi/node_modules/i2c/lib/i2c.coffee:60:9)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Here is my code

``` javascript
var oled = require('oled-js-pi');

var opts = {
  width: 128,
  height: 64,
  address: 0x3C
};

var oled = new oled(opts);

oled.clearDisplay();

oled.drawPixel([
    [128, 1, 1],
    [128, 32, 1],
    [128, 16, 1],
    [64, 16, 1]
]);
```

Here is the _transfer function from oled.js

``` javascript
// writes both commands and data buffers to this device
Oled.prototype._transfer = function(type, val, fn) {
  var control;
  if (type === 'data') {
    control = 0x40;
  } else if (type === 'cmd') {
    control = 0x00;
  } else {
    return;
  }

  // send control and actual val
  // this.board.io.i2cWrite(this.ADDRESS, [control, val]);
  this.wire.writeByte(control, function(err) {
    this.wire.writeByte(val, function(err) {
      fn();
    });
  });
}
```

It is failing on the `this.wire.writeByte(val, function(err) {` line...

Any help would be greatly appreciated.

**Comment by JMishou** [comment]
I found a work around.  Guess I was too tired to think last night as I was banging my head over this code. 

I simply changed this...

``` javascript
  this.wire.writeByte(control, function(err) {
    this.wire.writeByte(val, function(err) {
      fn();
    });
  });
```

to this... 

``` javascript
this.wire.write([control, val], function(err) {});
```

easy peasy.
