### ISSUE TITLE
TypeError: Failed to set address

### ISSUE THREAD

**Issue by chrisdew** [kd7yva/oled-js-pi#8]
I have a screen which is detected by the RPi:

<pre>
pi@raspberrypi:~/rxlora $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --     
</pre>

When I run the code:

<pre>
var ojp = require('oled-js-pi');
var font = require('oled-font-5x7');

var opts = {
  width: 128,
  height: 64,
  address: 0x3c //0x78
};

var oled = new ojp(opts);
oled.turnOnDisplay();
oled.clearDisplay();
oled.setCursor(1, 1);
oled.writeString(font, 1, 'Cats and dogs are really cool animals, you know.', 1, true);
</pre>

I get the error:

<pre>
pi@raspberrypi:~/rxlora $ node -v
v6.11.5
pi@raspberrypi:~/rxlora $ uname -a
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
/home/pi/rxlora/node_modules/i2c/lib/i2c.coffee:65
      wire.setAddress(address);
           ^

TypeError: Failed to set address
  at TypeError (native)
  at i2c.setAddress (/home/pi/rxlora/node_modules/i2c/lib/i2c.coffee:38:10)
  at i2c.writeByte (/home/pi/rxlora/node_modules/i2c/lib/i2c.coffee:57:6)
  at Oled._transfer (/home/pi/rxlora/node_modules/oled-js-pi/oled.js:120:13)
  at Oled._initialise (/home/pi/rxlora/node_modules/oled-js-pi/oled.js:103:10)
  at new Oled (/home/pi/rxlora/node_modules/oled-js-pi/oled.js:74:8)
  at Object.<anonymous> (/home/pi/rxlora/rxlora.js:11:12)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:383:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:496:3
</pre>

I'm using:

<pre>
pi@raspberrypi:~/rxlora $ node -v
v6.11.5
pi@raspberrypi:~/rxlora $ uname -a
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
pi@raspberrypi:~/rxlora $ grep "version" node_modules/oled-js-pi/package.json 
  "version": "1.0.5"
pi@raspberrypi:~/rxlora $ grep "version" node_modules/i2c/package.json 
  "version": "0.2.3"
</pre>

Why is this?

P.S. How do I tell oled-js-pi that the OLED is on i2c bus 1?

**Comment by chrisdew** [comment]
This issue occurs because the i2c bus is hard coded in https://github.com/juddflamm/oled-js-pi/blob/f76d62314e16bc1a1be1cffd66820a9fddd37aae/oled.js#L69 and is incorrect for an RPi3.
