### ISSUE TITLE
TypeError: "callback" argument must be a function

### ISSUE THREAD

**Issue by sltmunky69** [kd7yva/oled-js-pi#9]
I am simply trying to run the example code to test a display. I was able to get to this point after fixing the set address error for RPi3. Node v8.9.1

```
var oled = require('oled-js-pi');

var opts = {
  width: 128,
  height: 64,
  address: 0x3C
};

var oled = new oled(opts);

oled.turnOnDisplay();
oled.clearDisplay();

var font = require('oled-font-5x7');
oled.setCursor(1, 1);
oled.writeString(font, 1, 'Cats and dogs are really cool animals, you know.', 1, true);
```

```
TypeError: "callback" argument must be a function
  at setTimeout (timers.js:427:11)
  at Oled._waitUntilReady (/opt/node/oledtest/node_modules/oled-js-pi/oled.js:156:3)
  at Oled._updateDirtyBytes (/opt/node/oledtest/node_modules/oled-js-pi/oled.js:428:10)
  at Oled.clearDisplay (/opt/node/oledtest/node_modules/oled-js-pi/oled.js:341:10)
  at Object.<anonymous> (/opt/node/oledtest/oled.js:12:6)
  at Module._compile (module.js:635:30)
  at Object.Module._extensions..js (module.js:646:10)
  at Module.load (module.js:554:32)
  at tryModuleLoad (module.js:497:12)
  at Function.Module._load (module.js:489:3)
  at Function.Module.runMain (module.js:676:10)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3
```

Please advise.

**Comment by sltmunky69** [comment]
This appears to be a fork of oled-js, so I am just taking a stab in the dark here, should `setTimeout(tick(callback), 0);` possibly be `setTimeout(function(){tick(callback)}, 0);` instead?
